name: weather_clean_architecture_tdd
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.3
  get_it: ^7.2.0
  http: ^0.13.3
  rxdart: ^0.27.3
  hooks_riverpod: ^2.4.1
  go_router: ^11.1.2
  flutter_easylogger: ^2.3.3
  fpdart: ^0.5.0
  sizer: ^2.0.15
  intl: ^0.18.0
  rive: ^0.10.1
  gap: ^2.0.0
  google_fonts: ^4.0.3
  flex_color_scheme: ^6.0.1
  eva_icons_flutter: ^3.1.0
  cached_network_image: ^3.2.2
  iconly: ^1.0.1
  bot_toast: ^4.0.3
  hive_flutter: ^1.1.0
  dropdown_button2: ^2.0.0
  flutter_spinkit: ^5.1.0
  flutter_rating_bar: ^4.0.1
  readmore: ^2.2.0
  timelines: ^0.1.0

dev_dependencies:
  build_runner: ^2.1.2
  flutter_test:
    sdk: flutter
  mockito: ^5.0.15
  mocktail: ^0.2.0
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

